name: Build

on:
  pull_request:
  workflow_dispatch:
  # push: we actully don't need to test it on main because Vercel won't update prod without building

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-lint:
    name: Build and Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Get nodejs version from .nvmrc
        id: nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          setup-node: true
          node-version: ${{ env.NODE_VERSION }}
          audit: true

      - name: Lint
        uses: ./.github/actions/lint

      - name: Build
        uses: ./.github/actions/build

  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ukorvl/custom-github-actions-playwright:latest
      options: --user pwuser
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          setup-node: true
          audit: false

      - name: Build
        uses: ./.github/actions/build

      - name: Run E2E tests
        working-directory: frontend
        run: |
          export CI=true
          npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/tests/e2e/output/playwright-report
          if-no-files-found: "warn"
          retention-days: 30

  frontend-unit-tests:
    name: Unit Tests / Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          setup-node: true
          audit: false

      - name: Run frontend unit tests
        working-directory: frontend
        run: npm run test:unit

  sdk-unit-tests:
    name: Unit Tests / SDK
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          setup-node: true
          audit: false

      - name: Run SDK unit tests
        working-directory: sdk-js
        run: npm run test:unit

  ui-kit-unit-tests:
    name: Unit Tests / UI Kit
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          setup-node: true
          audit: false

      - name: Run UI Kit unit tests
        working-directory: ui-kit
        run: npm run test:unit

  indexer-unit-tests:
    name: Unit Tests / Indexer
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          setup-node: true
          audit: false

      - name: Run Indexer unit tests
        working-directory: indexer
        run: npm run test:unit
